# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af7ff045c3e32aa25449e86c65587904083a33faeae97b7134597eab647c8626123fb7bd2f38008134932ca3297e7433c2c20cf0fc0de5e202b2f07156633d5

test:
  secret_key_base: 4ccea7a738501162222debb13d805865250f80184b2d2d43f817346756f3b5f45360d4da2f03cfa5f3c7b14a41a0966f3222826aa9dd4ac1f31cc27da91c2b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
